name: 'Release'

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'yarn'

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check release version
        id: release_version
        run: echo "release_version='$(yarn --silent release:version)'" >> "$GITHUB_OUTPUT"

      - name: Print version
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build --no-cache --pull -t ghcr.io/ddeath/testing-playground:${{ steps.release_version.outputs.release_version }} . -f Dockerfile

      - name: Tag Docker Image with Latest
        run: docker tag ghcr.io/ddeath/testing-playground:${{ steps.release_version.outputs.release_version }} ghcr.io/ddeath/testing-playground:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/ddeath/testing-playground:${{ steps.release_version.outputs.release_version }}
          docker push ghcr.io/ddeath/testing-playground:latest
